name: Sync Models to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: git lfs install

      - name: Push to Hugging Face Model Repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "riteekgore37@gmail.com"
          git config --global user.name "riteekgore"

          git remote add hf https://riteekgore:$HF_TOKEN@huggingface.co/riteekgore/ai-fitness-coach-models
          git push hf main --force
